# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: I'm Ellen. This is Cactus.Works.
author: Ellen Manuszak
email: ellen@cactus.works
description: > # this means to ignore newlines until "baseurl:"
  I'm Ellen Manuszak. I write user interface code and html emails. Cactus.Works is front end development, HTML emails, and user experience design in Brooklyn.
baseurl: ""
url: "https://cactus.works" # the base hostname & protocol for your site
sns_username:  emanuszak
sass:
    style: compressed
    sass_dir: _sass

plugins: ['susy', 'breakpoint', 'jekyll-sitemap']

# Build settings
markdown: kramdown
theme: minima

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "main"
      title: "I'm Ellen. This is Cactus.Works"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      category: "blog"

collections_dir: collections
collections:
  clients:
    output: true
  products:
    output: false
  services:
    output: true